version: '3.8'

services:
  app-hsl:
    container_name: app-hsl
    image: node:18.12-alpine3
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres-hsl
    volumes:
      - ./src:/app/src
    networks:
      - hsl_net

  postgres-hsl:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: postgres-hsl
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # DATABASE_URL: ${DATABASE_URL}
      PGDATA: /var/lib/postgresql/data/hsl
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
    ports:
      - ${DB_PORT}:5432
    networks:
      - hsl_net
    expose:
      - 5432
    restart: unless-stopped

  # pgadmin:
  #   links:
  #     - postgres-hsl:postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   env_file:
  #     - .env
  #   networks:
  #     - hsl_net

volumes:
  pgdata:
  pglogs:

networks:
  hsl_net:
    driver: bridge
